services:
  db:
    image: mysql:8.0
    container_name: library-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: library_v1
      MYSQL_USER: mike
      MYSQL_PASSWORD: guang000
      TZ: Asia/Taipei
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      # 如果你有 schema.sql / init.sql，放在 ./db/init/ 底下即可自動初始化
      - ./db/init:/docker-entrypoint-initdb.d
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  minio:
    image: minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    environment:
      MINIO_PROMETHEUS_AUTH_TYPE: public
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123456
      TZ: Asia/Taipei
    ports:
      - "9000:9000" # S3 API
      - "9090:9090" # Console
    volumes:
      - minio_data:/data
      - minio_config:/root/.minio
    command: server /data --console-address ":9090" -address ":9000"

  redis:
    image: redis:7
    container_name: library-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes


volumes:
  mysql_data:
  minio_data:
  redis_data:
  minio_config:
