spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:3306}/${DB_NAME:library_v1}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true&useSSL=false
    username: mike
    password: guang000

    druid:
      initial-size: 5
      min-idle: 15
      max-active: 30
      remove-abandoned-timeout: 180
      max-wait: 300000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000

      filters: stat,wall,log4j2

      stat-view-servlet:
        enabled: true
        loginUsername: root
        loginPassword: guang000
        allow:

      web-stat-filter:
        enabled: true
        session-stat-enable: true
        session-stat-max-count: 1000
        url-pattern: /*

      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      #使用資料庫索引，預設0
      database: 0
      #連線逾時時間
      timeout: 1800000
      password:
      lettuce:
        pool:
          max-wait: -1
          max-idle: 32
          min-idle: 5
          max-active: 1000

  file-storage:
    default-platform: minio-1
    thumbnail-suffix: ".min.jpg"
    minio:
      - platform: minio-1
        enable-storage: true
        access-key: zJqKm8JLdp5U9vUgqBX0
        secret-key: JN2nQh4s0GJDL3LEsPxTTuLRkGsT3eAO1hseNFI6
        end-point: http://127.0.0.1:9000
        bucket-name: library
        domain: http://127.0.0.1:9000/library/
        base-path: ""

    amazon-s3:
      - platform: r2-1
        enable-storage: true
        access-key: a438f10db782de2c6dbffabd27258410
        secret-key: 7c2cf6a5893d664e324c91f4c3ecfb6937bc0f9ca6784c8aefc353063cc6b722
        end-point: https://6457c53a3594064e7dbb2399dba10d85.r2.cloudflarestorage.com/
        bucket-name: library-pic-r2
        region: auto
        domain: https://pub-92eafd428bef4519a19bb458602d89cc.r2.dev
        base-path: ""




